openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Parro
  license:
    name: MIT
servers: []
paths: {}
components:
  schemas:
    Account:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string