openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Parro
  license:
    name: MIT
servers: []
paths: {}
security: []
components:
  securitySchemes: {}
  schemas:
    Coin:
      type: object
      required:
        - id
        - symbol
        - name
        - current_price
      properties:
        id:
          type: string
        symbol:
          type: string
        name:
          type: string
        current_price:
          type: Double